export const LOG_OUT = 'LOG_OUT';
export const LOG_IN = 'LOG_IN'
export const USER_DETAILS = 'USER_DETAILS'
export const START_LOADING = 'START_LOADING'
export const STOP_LOADING = 'STOP_LOADING'
export const USERS_LIST = 'USERS_LIST'
export const EDIT_LIST = 'EDIT_LIST'
export const DELETE_STUDENT_DATA = 'DELETE_STUDENT_DATA'
export const IS_NOTIFY="IS_NOTIFY"
export const NOTIFY_MESSAGE="NOTIFY_MESSAGE"
export const NOTIFY_TYPE="NOTIFY_TYPE"